project:
  type: website
  resources:
    - example.py
    - working_example.zip
  output-dir: ../../paneltime.github.io


website:
  title: "paneltime.github.io"
  sidebar:
    style: floating
    contents:
      - index.qmd           # appears first
      - attributes.qmd           # appears second
      - options.qmd 
      - custom_model.qmd
      - hfunc.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    math: mathjax
    template-engine: jinja
