project:
  type: website
  render:
    - "*.qmd"
    - "api/*.qmd"
    - "guide/*.qmd"
  resources:
    - example.py
    - working_example.zip
  output-dir: ../../paneltime.github.io


website:
  title: "paneltime"
  site-url: https://paneltime.github.io
  sidebar:
    style: docked
    contents:
      - index.qmd
      - section: "Quickstart"
        contents:
          - quickstart.qmd
      - section: "User Guide"
        contents:
          - guide/custom-likelihood-models.qmd
          - guide/heteroskedasticity-functions.qmd
      - section: "API Reference"
        contents:
          - api/index.qmd
          - api/results.qmd
          - api/fit-options.qmd
      - examples.qmd
      - migration.qmd
      - changelog.qmd

  navbar:
    right:
      - icon: github
        href: https://github.com/paneltime/paneltime

format:
  html:
    theme: cosmo
    toc: true
    math: mathjax
    template-engine: jinja
